### PR TITLE
Fix error in README.md

### PR DESCRIPTION
**Pull request by FrankenApps**
This took me quite some time to figure out, so proposing to fix it for future reference.

### CODE REVIEW

**Comment by jjhbw** [comment]
I don't think this is an error. This is valid ES6 and Typescript syntax. What exactly is unclear about it?

**Comment by FrankenApps** [comment]
The image data won't be displayed when I use the approach without `data:`. The Image will be inserted but contain no data.

**Comment by jjhbw** [comment]
I really doubt that this is cause of the problem you experienced. Note that this exact pattern can also be found in the unit tests:
https://github.com/guigrpa/docx-templates/blob/10b6e16b1693edaa808a0ccc856159eaa460617b/src/__tests__/templating.test.ts#L701-L705

I'm happy to be proven wrong, though. But please provide a minimal reproducible example of the problem that demonstrates this. 

While this PR may seem like an innocuous change, I would consider it a serious error in my mental model of the Typescript language if this minor syntactical change is the actual cause of your problem.

**Comment by FrankenApps** [comment]
I made a repro. I tested it on Windows 10 like that. Maybe there is a difference when using data urls (haven't tested this)? In that case my PR is wrong, but maybe this should then be pointed out in some way, because it would be a bit confusing IMHO.
[GithubRepro.zip](https://github.com/guigrpa/docx-templates/files/5395827/GithubRepro.zip)

**Comment by jjhbw** [comment]
I think i see the problem. In your reproduction case you have the following line:
```typescript
                return { width: 6, height: 6, /*data: */imageData, extension: '.jpg' };
```
This is ES6/TS shorthand for 
```typescript
                return { width: 6, height: 6, imageData: imageData, extension: '.jpg' };
```
I.e. your object has a property named `imageData`, while the IMAGE command expects a property named `data`.

If you simply do the below, you should be fine:
```typescript
                let data = fs.readFileSync(path.resolve(process.cwd(), 'test_image.jpg'));
                return { width: 6, height: 6, data, extension: '.jpg' };         
```

I think we've just identified the problem. Note that the returned object cannot be conveniently typechecked because `additionalJsContext` allows you to provide arbitrary functions.

I think a better error message from docx-templates should help here. I have made an issue for this that i'll pick up later (#158 ).

I'll close this PR now, as I think we've established that the problem is not with the README. Feel free to reopen if you disagree.

**Pull request closed without merging**
