### PR TITLE
Fix browser documentation

### PR DESCRIPTION
**Pull request by vdechef**
Signed-off-by: Vincent de Chefdebien <vincent.dechefdebien@scassi.com>

### CODE REVIEW

**Comment by guigrpa** [comment]
Hmmm... I think the original code in the docs was correct, wasn't it?

**Comment by vdechef** [comment]
No, it is missing a return, thus you cannot await readFile.
I used the example for my usage, that's how I realized this : you do not get the promise back when calling readFile, thus you cannot "then" it.

**Comment by guigrpa** [comment]
Hmmm... Notice there are no brackets in the `readFile()` definition. I mean, you can write either:

```js
const readFile = fd =>
 new Promise((resolve, reject) => {
    const reader = new FileReader();
    reader.onerror = reject;
    reader.onload = () => {
      resolve(reader.result);
    };
    reader.readAsArrayBuffer(fd);
  });
```

...or:

```js
const readFile = fd => {
  return new Promise((resolve, reject) => {
    const reader = new FileReader();
    reader.onerror = reject;
    reader.onload = () => {
      resolve(reader.result);
    };
    reader.readAsArrayBuffer(fd);
  });
};
```

But again, maybe I'm missing something…

**Comment by vdechef** [comment]
My bad, you're right. I did not see this.

2018-01-25 13:43 GMT+01:00 Guillermo Grau Panea <notifications@github.com>:

**Pull request closed without merging**
