### PR TITLE
support buffer template and output

### LINKED ISSUE #18: Allow reading from & writing to streams for node version
The node version requires using the filesystem.  I'd like to work with files that are not saved to disk (like pulling from a DB, running the report, and saving back to a DB).

### LINKED ISSUE #28: Feature request: template as Buffer, output as Buffer
It wold be nice if template support node Buffer and also output as node Buffer

something like this
```
let template = fs.readFileSync('./template.docx')
let report = await createReport({
    template,
    data: {id: 1},
    nodeBuffer: true, // or something else
  })
console.log('Is buffer?', report instanceof Buffer)
```

I try to make PR, but my laptop is Windows, some build tools are not working

### PR DESCRIPTION
**Pull request by johannordin**
resolves #28 and resolves #18 

I'm not used to using Flow so I've probably made some mistakes. Also the README could be better.

Suggestions for improvements?

BR

### CODE REVIEW

**Comment by johannordin** [comment]
@guigrpa Any feedback on this?

**Comment by vdechef** [comment]
I gave a look at your PR, it seems OK for me.
I would also like to have it merged. Thanks for this 👍

**Comment by guigrpa** [comment]
@johannordin Thanks for the PR, and sorry for keeping you waiting! @vdechef Thanks too for reviewing the PR!

I'm merging it now and will be updating the part of the docs, which is still a bit confusing.

**Comment by guigrpa** [comment]
Shipped in v2.8.0, thanks again!

**Comment by lwallent** [comment]
Great job @johannordin! One minor thing that hit me you was the missing *await* in the documentation.
`const buffer = createReport({`
It is not the actual buffer being returned but rather a promise

**Comment by guigrpa** [comment]
True! Updated.

**Pull request merged**
