### PR TITLE
Dynamic table columns feature

### PR DESCRIPTION
**Pull request by SuchiraD**
Added looping for table columns. 

Eg: 
Dynamic columns
image

image

Dynamic rows & dynamic columns
image

image

### CODE REVIEW

**Comment by SuchiraD** [comment]
Hey @guigrpa, I have made few changes to enable dynamic generation of table columns. Please suggest any test cases that I should add, which will cover any edge case if there is any.

**Comment by SuchiraD** [comment]
> Good to see someone finally took a stab at this! Thanks a lot for the effort.
> 
> Sorry for taking so long to respond to this, I have been meaning to test it against a few private test cases first to ensure we're not introducing regressions (the docx spec is terrifying, as you may know very well by now haha).


Hahaha.... absolutely. It is too complicated. 

Yes please. Its always better to look at this in another perspective. Maybe I could have been biased only for the repetition of table columns.

**Comment by SuchiraD** [comment]
Hi @jjhbw, 
Do you have any idea on what scenarios should I write more test cases to?

**Comment by jjhbw** [comment]
Working on your PR now.

RE `Ran `jest --updateSnapshot` to fix error_handling.test.ts.snap`; these snapshots weren't broken, they were just geared towards Node 20.x, which has different error messages than older versions.

**Comment by jjhbw** [comment]
Thanks! Looks great.

Merged offline 13b40c37d75d613351ea00b6d7dda0b64cc9c406

**Pull request closed without merging**
