### PR TITLE
added svg support for image tag.

### LINKED ISSUE #33: IMAGE command doesn't support .svg files
Hi!
I have noticed that trying to insert an svg file in the word document with the command +++IMAGE insertSvg()+++ always ends with the document broken and an image that cannot be displayed

image

Is there any plan to support SVG files? or maybe I'm missing something?
I'm using the same function to load a .png file and everything goes well.

### PR DESCRIPTION
**Pull request by lwallent**
Fixes #33
SVG images can be inserted using the IMAGE tag. The svg can be read from file or be injected from the js context. A thumbnail/fallback png needs to be specified.

### CODE REVIEW

**Comment by guigrpa** [comment]
That's awesome, thanks a lot for the effort!

While I'm reviewing this, what's the goal of the fallback png? I notice from the examples (**example-node/images-path_report.docx** and **example-node/images-svg_report.docx**) that the original SVG picture is not shown when you open the file in Word (at least in Word for Mac 15.x). Is it because my Word version does not support SVG?

Could you also comment on the large update to the test snapshot files? Why are these needed?

Thanks again! I look forward to merging this soon.

**Comment by lwallent** [comment]
Hi @guigrpa 
The goal of the png is to my knowledge twofold; 
1) When seeing a preview of the file (like in Finder (Mac)) it is the thumbnail/fallback image being shown.
2) In case the SVG image is not supported it will fallback to the png image. Looking at the structure of the generated XML, you will see that the fallback is placed where you would see the reference Id of normal graphics - this tells me that if the Word version does not understand the new SVG schema, it will just read the fallback image.

SVG is supported from version 16. I would have included a link, but it seems Microsoft have now moved things around in there release notes :-(

I guess the fact that I am using Word version 16 explains the big changes in the snapshot. I was actually wondering what to do about this fact when creating the Pull Request :-) I really like the use of Jest - especially for what you are doing in your *amazing* library, but I guess one needs to take application version into account some how :-)

Perhaps I should just have added an SVG only test, but I saw that you already had SVG images in the code, but they where not working, so I fixed that :-)

**Comment by raudabaugh** [comment]
Would it be possible to adapt this code for browser use? It looks like the thumbnail getter is expecting `fs` to be available.

**Comment by jjhbw** [comment]
This is some pretty great stuff! As this PR is already pretty old, i'll have to do some work on it first since the library has changed quite a bit since. If you want to contribute, feel free to fork `guigrpa:33-IMAGE-command-SVG-support`.

**Pull request merged**
